Target = {'AJ_b1': 0, 'AJ_b2': 0, 'FA_b1': 1, 'FA_b2': 1, 'FA_b3': 1}
#Control strategies using percolation
cs = [{'ROS': 1, ('ECM', 'ECM'): 1},
 {'ROS': 1, ('ITG_AB', 'FA_b3'): 1},
 {('ITG_AB', 'FA_b3'): 1, ('ROS', 'ROS'): 1},
 {'ECM': 1, 'ROS': 1},
 {'ECM': 1, ('ROS', 'ROS'): 1},
 {('ECM', 'ECM'): 1, ('ROS', 'ROS'): 1},
 {'ITG_AB': 1, ('ROS', 'ROS'): 1},
 {'ITG_AB': 1, 'JNK': 1},
 {'ITG_AB': 1, 'ROS': 1},
 {'ITG_AB': 1, ('RPTP', 'JNK'): 0},
 {'ITG_AB': 1, ('BCat', 'TCF_LEF'): 0},
 {'ITG_AB': 1, ('TCF_LEF', 'SNAIL'): 0},
 {'ITG_AB': 1, ('TGFBR', 'SMAD'): 1},
 {'ITG_AB': 1, ('SLUG', 'ECad'): 1},
 {'ITG_AB': 1, 'ZEB': 1},
 {'ITG_AB': 1, 'SLUG': 1},
 {'CSL': 1, 'ITG_AB': 1},
 {'ITG_AB': 1, ('JNK', 'SNAIL'): 1},
 {'ITG_AB': 1, ('miR200', 'SLUG'): 0},
 {'ITG_AB': 1, 'TCF_LEF': 0},
 {'ITG_AB': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b2': 1, 'ITG_AB': 1},
 {'ITG_AB': 1, 'TGFB': 1},
 {'ITG_AB': 1, 'RPTP_L': 0},
 {'ITG_AB': 1, ('TGFB', 'TGFB'): 1},
 {'ITG_AB': 1, ('FAK_SRC_b2', 'RPTP'): 1},
 {'ITG_AB': 1, ('RPTP_L', 'RPTP_L'): 0},
 {'ITG_AB': 1, 'SMAD': 1},
 {'ITG_AB': 1, 'TGFBR': 1},
 {'ITG_AB': 1, 'RPTP': 0},
 {'ITG_AB': 1, ('CSL', 'SNAIL'): 1},
 {'ITG_AB': 1, ('SMAD', 'SNAIL'): 1},
 {'ITG_AB': 1, ('ROS', 'FAK_SRC_b2'): 1},
 {'ITG_AB': 1, 'SNAIL': 1},
 {'ECad': 0, 'ITG_AB': 1},
 {'ITG_AB': 1, ('ZEB', 'miR200'): 1},
 {'BCat': 0, 'ITG_AB': 1},
 {'ITG_AB': 1, ('SNAIL', 'miR200'): 1},
 {'ITG_AB': 1, 'miR200': 0}]
