Target = {'AJ_b1': 0, 'AJ_b2': 0, 'FA_b1': 1, 'FA_b2': 1, 'FA_b3': 0}
#Control strategies using percolation
cs = [{('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0},
 {('RAP1', 'ITG_AB'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'ROS'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'ROS'): 1},
 {('ECM', 'ECM'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('TGFB', 'TGFB'): 1},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('BCat', 'TCF_LEF'): 0,
  ('FAK_SRC_b1', 'RAP1'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FA_b1', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FA_b2', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FA_b1', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FA_b2', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('RAP1', 'ITG_AB'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('RAP1', 'ITG_AB'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('RAP1', 'ITG_AB'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('FA_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ECM'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('RAP1', 'ITG_AB'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('RAP1', 'ITG_AB'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('PAK', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('PAK', 'FA_b3'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('FAK_SRC_b1', 'FA_b2'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('FAK_SRC_b1', 'FA_b2'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ROS', 'FAK_SRC_b1'): 1,
  ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('BCat', 'TCF_LEF'): 0, ('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0},
 {('BCat', 'TCF_LEF'): 0,
  ('EGFR', 'FAK_SRC_b1'): 1,
  ('FAK_SRC_b1', 'FA_b3'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('PAK', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('PAK', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('BCat', 'TCF_LEF'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFBR', 'SMAD'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SMAD', 'SNAIL'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('ZEB', 'ECad'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SLUG', 'ECad'): 1},
 {('BCat', 'TCF_LEF'): 0,
  ('FAK_SRC_b1', 'FA_b3'): 0,
  ('HGFR', 'FAK_SRC_b1'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('HGFR', 'FAK_SRC_b1'): 1,
  ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFBR', 'SMAD'): 1},
 {('BCat', 'TCF_LEF'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('ZEB', 'miR200'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('miR200', 'SLUG'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1,
  ('FAK_SRC_b1', 'FA_b3'): 0,
  ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFB'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('BCat', 'TCF_LEF'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('miR200', 'SLUG'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFBR'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TGFBR', 'SMAD'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('ZEB', 'ECad'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('ZEB', 'miR200'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SMAD', 'SNAIL'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('HGFR', 'FAK_SRC_b1'): 1,
  ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0,
  ('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('ZEB', 'miR200'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('SNAIL', 'miR200'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ECM'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b2', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ECM'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('RAP1', 'ITG_AB'): 0, ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1,
  ('FAK_SRC_b1', 'FA_b3'): 0,
  ('SNAIL', 'miR200'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('ITG_AB', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0,
  ('HGFR', 'FAK_SRC_b1'): 1,
  ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1,
  ('FAK_SRC_b1', 'RAP1'): 0,
  ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FAK_SRC_b1', 'RAP1'): 0, ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0,
  ('ITG_AB', 'FAK_SRC_b1'): 1,
  ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFB'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'RPTP'): 1, ('TGFB', 'TGFBR'): 1},
 {('PAK', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFB'): 1},
 {('PAK', 'FA_b3'): 0, ('RPTP_L', 'RPTP'): 0, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('ITG_AB', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFBR', 'SMAD'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SMAD', 'SNAIL'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('ZEB', 'miR200'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('miR200', 'SLUG'): 0},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('ZEB', 'ECad'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SLUG', 'ECad'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFBR'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('HGFR', 'FAK_SRC_b1'): 1, ('PAK', 'FA_b3'): 0, ('SNAIL', 'miR200'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('BCat', 'TCF_LEF'): 0, ('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFBR'): 1},
 {('ECM', 'ITG_AB'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1}]
