Target = {'AJ_b1': 0, 'AJ_b2': 0, 'FA_b1': 1, 'FA_b2': 0, 'FA_b3': 0}
#Control strategies using percolation
cs = [{'PI3K': 0, ('FAK_SRC_b1', 'PAK'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('PAK', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FA_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FA_b2', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FA_b3', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FA_b2', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'PAK'): 0, ('PI3K', 'PAK'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('ITG_AB', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b1', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b3', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {'ZEB': 1, ('FAK_SRC_b1', 'PAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('BCat', 'TCF_LEF'): 0},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'TCF_LEF': 0},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'ROS': 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('EGF', 'EGF'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'ROS': 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'TCF_LEF': 0},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('ITG_AB', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b3', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'ECM': 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFB'): 1},
 {'PAK': 0, 'TGFB': 1, ('RPTP_L', 'RPTP_L'): 0},
 {'PAK': 0, 'TGFBR': 1, ('RPTP_L', 'RPTP_L'): 0},
 {'PAK': 0, 'RPTP_L': 0, 'TGFB': 1},
 {'PAK': 0, 'RPTP_L': 0, 'TGFBR': 1},
 {'PAK': 0, ('ROS', 'ROS'): 1},
 {'PAK': 0, 'ROS': 1},
 {'FAK_SRC_b1': 0, 'TGFB': 1},
 {'FAK_SRC_b1': 0, 'TGFBR': 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('PAK', 'FA_b1'): 1},
 {'FAK_SRC_b1': 0, ('PAK', 'FA_b1'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('PAK', 'FA_b1'): 1},
 {'PI3K': 0, 'ROS': 1, ('FAK_SRC_b1', 'PAK'): 0},
 {('ITG_AB', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b2', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {('FA_b3', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'ECM': 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('ITG_AB', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFB': 1, ('FA_b2', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFB': 1, ('FA_b3', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0},
 {'ECM': 0, 'TGFB': 1, ('PAK', 'FA_b2'): 0},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b3'): 0},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b3', 'FA_b2'): 0},
 {'ECM': 0, 'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('ITG_AB', 'FA_b3'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b3'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b3', 'FA_b2'): 0},
 {'ECM': 0, 'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('ITG_AB', 'FA_b3'): 0},
 {'TGFBR': 1, ('FA_b2', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFBR': 1, ('FA_b3', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0},
 {'ECM': 0, 'TGFBR': 1, ('PAK', 'FA_b2'): 0},
 {'TGFBR': 1, ('ITG_AB', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b1', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b1', 'FA_b3'): 0},
 {('FA_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FA_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b1', 'FA_b3'): 0},
 {'TGFBR': 1, ('FA_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0},
 {('PAK', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('PAK', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0},
 {'TGFBR': 1, ('PAK', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'FA_b3'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'FA_b3'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'FA_b3'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b2'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b2'): 0},
 {('FA_b2', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFB': 1, ('FA_b2', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFBR': 1, ('FA_b2', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFB': 1, ('FA_b1', 'FA_b2'): 0},
 {('FA_b1', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFBR': 1, ('FA_b1', 'FA_b2'): 0},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('SMAD', 'SNAIL'): 1},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('miR200', 'SLUG'): 0},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1, ('TGFBR', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'PAK': 0, 'TGFB': 1, ('RPTP', 'EGFR'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b3'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b3', 'FA_b2'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('ITG_AB', 'FA_b3'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b1', 'FA_b3'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'FA_b3'): 0},
 {'ROS': 1, ('FA_b2', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'ROS': 1, ('FA_b3', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0},
 {'ROS': 1, ('ITG_AB', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'ROS': 1, ('FA_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'ROS': 1, ('PAK', 'FA_b2'): 0, ('PAK', 'FA_b3'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b3'): 0, ('PAK', 'FA_b2'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FA_b2', 'FA_b2'): 0},
 {'ROS': 1, ('FA_b2', 'FA_b2'): 0, ('PAK', 'FA_b2'): 0},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {'ROS': 1, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('PAK', 'FA_b1'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('PAK', 'FA_b1'): 1},
 {'SNAIL': 1, ('FAK_SRC_b1', 'PAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('PAK', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0, ('ROS', 'ROS'): 1},
 {('PAK', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0, ('ROS', 'ROS'): 1},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0},
 {'ROS': 1, ('PAK', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0},
 {'ECM': 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {'ECM': 0, 'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'ECM': 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {'ECM': 0, 'ROS': 1, ('PAK', 'FA_b2'): 0},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('SMAD', 'SNAIL'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'SMAD': 1, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'SLUG': 1, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'SNAIL': 1, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'ECad': 0, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'miR200': 0, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('FAK_SRC_b1', 'PAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'PAK'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'PAK'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, ('FAK_SRC_b1', 'PAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('PAK', 'FA_b1'): 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0},
 {'TGFB': 1, ('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'ROS': 1, ('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'TGFBR': 1, ('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 0},
 {('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('ECM', 'ECM'): 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('HGFR', 'RAS'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('HGFR', 'RAS'): 1},
 {'TGFB': 1, ('PAK', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0},
 {'TGFBR': 1, ('PAK', 'FA_b2'): 0, ('RAP1', 'ITG_AB'): 0},
 {'TGFB': 1, ('ECM', 'ECM'): 0, ('PAK', 'FA_b2'): 0},
 {('ECM', 'ECM'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'TGFBR': 1, ('ECM', 'ECM'): 0, ('PAK', 'FA_b2'): 0},
 {'ROS': 1, ('ECM', 'ECM'): 0, ('PAK', 'FA_b2'): 0},
 {('ECM', 'ECM'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('ZEB', 'miR200'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('IL6', 'IL6'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, 'TCF_LEF': 0, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('JAK', 'RAS'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'TCF_LEF': 0, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('RAS', 'PI3K'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('ZEB', 'miR200'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, 'TCF_LEF': 0, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('SNAIL', 'miR200'): 1, ('TGFBR', 'RAS'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'TCF_LEF': 0, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('SNAIL', 'miR200'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'TCF_LEF': 0, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('RAS', 'PI3K'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('PAK', 'FA_b1'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('TGFB', 'TGFB'): 1},
 {'FAK_SRC_b1': 0, 'HGF': 1, 'ROS': 1},
 {'FAK_SRC_b1': 0, 'HGF': 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, ('EGF', 'EGF'): 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'SMAD': 1, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'SMAD': 1, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'SMAD': 1, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('ROS', 'ROS'): 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'SMAD': 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, ('SMAD', 'SNAIL'): 1, ('TGFBR', 'RAS'): 1},
 {'EGF': 1, 'FAK_SRC_b1': 0, 'ROS': 1},
 {'EGF': 1, 'FAK_SRC_b1': 0, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'ROS': 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'SLUG': 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, 'RAS': 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'SMAD': 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'SNAIL': 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('SMAD', 'SNAIL'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, 'RAS': 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'SLUG': 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, 'IL6': 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'ROS': 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'SMAD': 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'SNAIL': 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, 'IL6': 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('ZEB', 'miR200'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('SNAIL', 'miR200'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'SLUG': 1},
 {'CSL': 1, 'EGFR': 1, 'FAK_SRC_b1': 0},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('ROS', 'ROS'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'SMAD': 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('TGFBR', 'SMAD'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('SMAD', 'SNAIL'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'SNAIL': 1},
 {'BCat': 0, 'EGFR': 1, 'FAK_SRC_b1': 0},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'ZEB': 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('RAS', 'PI3K'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'ZEB': 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'ZEB': 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'SLUG': 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, 'JAK': 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'ROS': 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'SMAD': 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'ZEB': 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'SNAIL': 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, 'JAK': 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'SMAD': 1, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'PI3K': 1, 'SLUG': 1},
 {'FAK_SRC_b1': 0, 'PI3K': 1, 'SNAIL': 1},
 {'FAK_SRC_b1': 0, 'PI3K': 1, 'ZEB': 1},
 {'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'RAP1'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'RAP1'): 0},
 {'TGFB': 1, ('FAK_SRC_b1', 'RAP1'): 0, ('PAK', 'FA_b2'): 0},
 {'TGFBR': 1, ('FAK_SRC_b1', 'RAP1'): 0, ('PAK', 'FA_b2'): 0},
 {'RAP1': 0, 'TGFB': 1, ('PAK', 'FA_b2'): 0},
 {'RAP1': 0, 'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'RAP1': 0, 'TGFBR': 1, ('PAK', 'FA_b2'): 0},
 {'RAP1': 0, 'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'RAP1': 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'RAP1'): 0, ('TGFB', 'TGFB'): 1},
 {'RAP1': 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'ITG_AB': 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'ITG_AB': 0, 'TGFBR': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'ITG_AB': 0, 'TGFB': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'ITG_AB': 0, 'TGFB': 1, ('PAK', 'FA_b2'): 0},
 {'ITG_AB': 0, 'TGFBR': 1, ('PAK', 'FA_b2'): 0},
 {'ITG_AB': 0, ('PAK', 'FA_b2'): 0, ('TGFB', 'TGFB'): 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'TGFB': 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'TGFBR': 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('TGFB', 'TGFB'): 1},
 {'ROS': 1, ('FAK_SRC_b1', 'PAK'): 0, ('PI3K', 'PAK'): 0},
 {'PAK': 0, 'TGFBR': 1, ('RPTP', 'EGFR'): 0},
 {'PAK': 0, ('RPTP', 'EGFR'): 0, ('TGFB', 'TGFB'): 1},
 {'RAP1': 0, 'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'RAP1': 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {'ITG_AB': 0, 'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0},
 {'ITG_AB': 0, ('FAK_SRC_b1', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'ROS'): 1},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b2'): 0, ('FAK_SRC_b1', 'RAP1'): 0},
 {'ROS': 1, ('FAK_SRC_b1', 'RAP1'): 0, ('PAK', 'FA_b2'): 0},
 {'RAP1': 0, 'ROS': 1, ('PAK', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'SLUG': 1, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, 'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('FAK_SRC_b1', 'PI3K'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'SLUG': 1, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'RAP1': 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('ZEB', 'miR200'): 1},
 {'ITG_AB': 0, 'ROS': 1, ('PAK', 'FA_b2'): 0},
 {'ITG_AB': 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {('FAK_SRC_b1', 'RAP1'): 0, ('PAK', 'FA_b2'): 0, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('ZEB', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('SNAIL', 'miR200'): 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('HGFR', 'RAS'): 1},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('RPTP_L', 'RPTP_L'): 0, ('TGFB', 'TGFB'): 1},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'IL6': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'PI3K': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'JAK': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'PI3K': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'IL6': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'JAK': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'PI3K': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'IL6': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'JAK': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'SNAIL': 1, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('RAS', 'PI3K'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('RAS', 'PI3K'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('RAS', 'PI3K'): 1},
 {'PAK': 0, 'TGFB': 1, ('FAK_SRC_b1', 'FA_b1'): 1},
 {'PAK': 0, 'TGFBR': 1, ('FAK_SRC_b1', 'FA_b1'): 1},
 {'PAK': 0, ('FAK_SRC_b1', 'FA_b1'): 1, ('TGFB', 'TGFB'): 1},
 {'FAK_SRC_b1': 0, 'ITG_AB': 1, 'ROS': 1},
 {'FAK_SRC_b1': 0, 'ITG_AB': 1, ('ROS', 'ROS'): 1},
 {'PAK': 0, 'RPTP_L': 0, ('TGFB', 'TGFB'): 1},
 {'PAK': 0, 'RPTP': 0, 'TGFB': 1},
 {'PAK': 0, 'RPTP': 0, 'TGFBR': 1},
 {'PAK': 0, 'RPTP': 0, ('TGFB', 'TGFB'): 1},
 {'SLUG': 1, ('FAK_SRC_b1', 'FA_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('FAK_SRC_b1', 'FA_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SNAIL': 1, ('FAK_SRC_b1', 'FA_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'PAK': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'PAK': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'PAK': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('PI3K', 'PAK'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('PI3K', 'PAK'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('PI3K', 'PAK'): 1},
 {'EGFR': 1, 'PAK': 0, ('SNAIL', 'miR200'): 1},
 {'EGFR': 1, 'PAK': 0, ('ZEB', 'miR200'): 1},
 {'EGFR': 1, 'PAK': 0, 'TGFB': 1},
 {'CSL': 1, 'EGFR': 1, 'PAK': 0},
 {'EGFR': 1, 'PAK': 0, 'SNAIL': 1},
 {'EGFR': 1, 'PAK': 0, 'TGFBR': 1},
 {'EGFR': 1, 'PAK': 0, 'SLUG': 1},
 {'EGFR': 1, 'PAK': 0, 'ZEB': 1},
 {'EGFR': 1, 'PAK': 0, ('TGFB', 'TGFB'): 1},
 {'EGFR': 1, 'PAK': 0, ('TGFBR', 'SMAD'): 1},
 {'EGFR': 1, 'PAK': 0, 'SMAD': 1},
 {'HGFR': 1, 'PAK': 0, 'TGFBR': 1},
 {'HGFR': 1, 'PAK': 0, ('SNAIL', 'miR200'): 1},
 {'HGFR': 1, 'PAK': 0, ('ZEB', 'miR200'): 1},
 {'HGFR': 1, 'PAK': 0, 'TGFB': 1},
 {'HGFR': 1, 'PAK': 0, 'SLUG': 1},
 {'CSL': 1, 'HGFR': 1, 'PAK': 0},
 {'HGFR': 1, 'PAK': 0, ('TGFB', 'TGFB'): 1},
 {'HGFR': 1, 'PAK': 0, 'ZEB': 1},
 {'HGFR': 1, 'PAK': 0, 'SNAIL': 1},
 {'HGFR': 1, 'PAK': 0, ('TGFBR', 'SMAD'): 1},
 {'HGFR': 1, 'PAK': 0, 'SMAD': 1},
 {'PAK': 0, 'SLUG': 1, ('FAK_SRC_b1', 'FA_b1'): 1},
 {'PAK': 0, 'ZEB': 1, ('FAK_SRC_b1', 'FA_b1'): 1},
 {'PAK': 0, 'SNAIL': 1, ('FAK_SRC_b1', 'FA_b1'): 1},
 {'EGFR': 1, 'PAK': 0, ('SMAD', 'SNAIL'): 1},
 {'HGFR': 1, 'PAK': 0, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, 'PAK': 1, 'SNAIL': 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'PAK': 1, 'ZEB': 1},
 {'FAK_SRC_b1': 0, 'PAK': 1, 'SLUG': 1},
 {'FAK_SRC_b1': 0, 'SMAD': 1, ('HGFR', 'RAS'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 0, 'HGFR': 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'SNAIL': 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'SLUG': 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('ROS', 'ROS'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'ZEB': 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'SMAD': 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('TGFBR', 'EGFR'): 1},
 {'FAK_SRC_b1': 0, ('ROS', 'ROS'): 1, ('TGFBR', 'EGFR'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('SMAD', 'SNAIL'): 1},
 {'HGFR': 1, 'PAK': 0, ('BCat', 'TCF_LEF'): 0},
 {'HGFR': 1, 'PAK': 0, ('TCF_LEF', 'SNAIL'): 0},
 {'HGFR': 1, 'PAK': 0, ('ZEB', 'ECad'): 1},
 {'HGFR': 1, 'PAK': 0, ('miR200', 'SLUG'): 0},
 {'HGFR': 1, 'PAK': 0, ('SLUG', 'ECad'): 1},
 {'HGFR': 1, 'PAK': 0, 'TCF_LEF': 0},
 {'ECad': 0, 'HGFR': 1, 'PAK': 0},
 {'HGFR': 1, 'PAK': 0, 'miR200': 0},
 {'BCat': 0, 'HGFR': 1, 'PAK': 0},
 {'EGFR': 1, 'PAK': 0, ('TCF_LEF', 'SNAIL'): 0},
 {'EGFR': 1, 'PAK': 0, ('BCat', 'TCF_LEF'): 0},
 {'EGFR': 1, 'PAK': 0, ('miR200', 'SLUG'): 0},
 {'EGFR': 1, 'PAK': 0, ('SLUG', 'ECad'): 1},
 {'EGFR': 1, 'PAK': 0, ('ZEB', 'ECad'): 1},
 {'EGFR': 1, 'PAK': 0, 'TCF_LEF': 0},
 {'ECad': 0, 'EGFR': 1, 'PAK': 0},
 {'EGFR': 1, 'PAK': 0, 'miR200': 0},
 {'BCat': 0, 'EGFR': 1, 'PAK': 0},
 {'PAK': 0, ('FAK_SRC_b1', 'FA_b1'): 1, ('SLUG', 'ECad'): 1},
 {'PAK': 0, ('FAK_SRC_b1', 'FA_b1'): 1, ('ZEB', 'ECad'): 1},
 {'ECad': 0, 'PAK': 0, ('FAK_SRC_b1', 'FA_b1'): 1},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('ZEB', 'miR200'): 1},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('SNAIL', 'miR200'): 1},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'BCat': 0, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'BCat': 0, 'IL6': 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, 'JAK': 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'BCat': 0, 'RAS': 1, ('FA_b1', 'FA_b2'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'JAK': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {'IL6': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {('BCat', 'TCF_LEF'): 0, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'RAS': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'TCF_LEF': 0, ('EGFR', 'JAK'): 1, ('FA_b1', 'FA_b2'): 0},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('JAK', 'RAS'): 1},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('IL6', 'IL6'): 1},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'IL6': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'JAK': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'TCF_LEF': 0, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'TCF_LEF': 0, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'RAS': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0, ('TGFBR', 'RAS'): 1},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {'IL6': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'JAK': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'miR200': 0, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'miR200': 0, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'RAS': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {'ZEB': 1, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'RAS': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1, ('TGFBR', 'RAS'): 1},
 {'SNAIL': 1, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('TGFBR', 'SMAD'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('SMAD', 'SNAIL'): 1},
 {'RAS': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'CSL': 1, 'JAK': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, 'IL6': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, 'RAS': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'CSL': 1, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'RAS': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('PAK', 'FA_b1'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('RAS', 'PI3K'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('PAK', 'FA_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('RAS', 'PI3K'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('PAK', 'FA_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('RAS', 'PI3K'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('TGFBR', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1, ('TGFBR', 'RAS'): 1},
 {'ECad': 0, 'PAK': 1, ('FA_b1', 'FA_b2'): 0},
 {'PAK': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'PAK': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SMAD': 1, ('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, 'PI3K': 1, ('FA_b1', 'FA_b2'): 0},
 {'PI3K': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'PI3K': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, 'RAS': 1, ('FA_b1', 'FA_b2'): 0},
 {'RAS': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'RAS': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, 'JAK': 1, ('FA_b1', 'FA_b2'): 0},
 {'JAK': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'JAK': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ECad': 0, 'IL6': 1, ('FA_b1', 'FA_b2'): 0},
 {'IL6': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'SMAD': 1, ('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {('EGFR', 'RAS'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'IL6': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'miR200': 0, ('EGFR', 'JAK'): 1},
 {'FAK_SRC_b1': 0, 'miR200': 0, ('IL6', 'IL6'): 1},
 {'FAK_SRC_b1': 0, 'miR200': 0, ('JAK', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('RAS', 'PI3K'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('PAK', 'FA_b1'): 1},
 {'ZEB': 1, ('FAK_SRC_b1', 'PI3K'): 1, ('FA_b1', 'FA_b2'): 0},
 {'SNAIL': 1, ('FAK_SRC_b1', 'PI3K'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ECad': 0, ('FAK_SRC_b1', 'PI3K'): 1, ('FA_b1', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'PI3K'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {('FAK_SRC_b1', 'PI3K'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'EGFR': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, 'EGFR': 1, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'EGFR': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'BCat': 0, 'EGFR': 1, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'EGFR': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {'ECad': 0, 'EGFR': 1, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {'EGFR': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, 'IL6': 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, 'JAK': 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, 'PAK': 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'PAK': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'JAK'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('IL6', 'IL6'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('JAK', 'RAS'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'PAK': 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('RAS', 'PI3K'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('RAS', 'PI3K'): 1, ('ZEB', 'ECad'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, 'PI3K': 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('PAK', 'FA_b1'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'TCF_LEF': 0},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('BCat', 'TCF_LEF'): 0},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, 'IL6': 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, 'IL6': 1, 'miR200': 0},
 {'FAK_SRC_b1': 0, 'PI3K': 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'PI3K': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'TCF_LEF': 0},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('BCat', 'TCF_LEF'): 0},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('TCF_LEF', 'SNAIL'): 0},
 {'ECad': 0, 'FAK_SRC_b1': 0, 'RAS': 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'RAS': 1, 'miR200': 0},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, 'RAS': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('TCF_LEF', 'SNAIL'): 0, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('SLUG', 'ECad'): 1, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, 'miR200': 0, ('TGFBR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, ('TGFBR', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'miR200': 0, ('EGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('EGFR', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'TCF_LEF': 0},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('BCat', 'TCF_LEF'): 0},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 0, 'JAK': 1, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, 'JAK': 1, 'miR200': 0},
 {'BCat': 0, 'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('BCat', 'TCF_LEF'): 0, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'TCF_LEF': 0, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'miR200': 0, ('HGFR', 'RAS'): 1},
 {'FAK_SRC_b1': 0, ('HGFR', 'RAS'): 1, ('miR200', 'SLUG'): 0},
 {'ECad': 0, 'EGFR': 1, 'FAK_SRC_b1': 0},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('SLUG', 'ECad'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('ZEB', 'ECad'): 1},
 {'EGFR': 1, 'FAK_SRC_b1': 0, 'miR200': 0},
 {'EGFR': 1, 'FAK_SRC_b1': 0, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'CSL': 1, 'FAK_SRC_b1': 1, 'PAK': 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'SNAIL': 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'ZEB': 1},
 {'FAK_SRC_b1': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, 'FAK_SRC_b1': 1, 'PAK': 0},
 {'BCat': 0, 'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'SLUG': 1},
 {'FAK_SRC_b1': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'ECad': 0, 'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'ECad': 0, 'FAK_SRC_b1': 1, 'PAK': 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'SMAD': 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'miR200': 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('BCat', 'TCF_LEF'): 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, 'TCF_LEF': 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('ITG_AB', 'HGFR'): 1},
 {'FAK_SRC_b1': 0, ('ITG_AB', 'HGFR'): 1, ('ROS', 'ROS'): 1},
 {'PAK': 0, 'TGFB': 1, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TGFBR': 1, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {'ECad': 0, ('FAK_SRC_b1', 'FA_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {('FAK_SRC_b1', 'FA_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {('FAK_SRC_b1', 'FA_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('PI3K', 'PAK'): 1},
 {('FA_b1', 'FA_b2'): 0, ('PI3K', 'PAK'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('PI3K', 'PAK'): 1, ('ZEB', 'ECad'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {'CSL': 1, 'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SLUG': 1, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SNAIL': 1, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'ZEB': 1, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'PAK': 0, 'SMAD': 1, ('HGFR', 'FAK_SRC_b1'): 1},
 {'BCat': 0, 'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'PAK': 0, ('BCat', 'TCF_LEF'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TCF_LEF': 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'ECad': 0, 'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {'PAK': 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {'PAK': 0, 'miR200': 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'BCat': 0, 'FAK_SRC_b1': 0, 'HGFR': 1},
 {'FAK_SRC_b1': 0, 'ROS': 1, ('HGF', 'HGF'): 1},
 {'FAK_SRC_b1': 0, ('HGF', 'HGF'): 1, ('ROS', 'ROS'): 1},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'BCat': 0, 'HGFR': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, 'HGFR': 1, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'HGFR': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {'ECad': 0, 'HGFR': 1, ('FA_b1', 'FA_b2'): 0},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'HGFR': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'PAK': 0, 'TGFB': 1, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TGFBR': 1, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {'PAK': 0, 'SLUG': 1, ('EGFR', 'FAK_SRC_b1'): 1},
 {'CSL': 1, 'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {'BCat': 0, 'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TGFB': 1, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TGFBR': 1, ('ROS', 'FAK_SRC_b1'): 1},
 {'CSL': 1, 'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {'PAK': 0, 'SLUG': 1, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TGFB': 1, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TGFBR': 1, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'CSL': 1, 'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFB', 'TGFB'): 1},
 {'PAK': 0, 'SLUG': 1, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {'PAK': 0, 'SNAIL': 1, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SNAIL': 1, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'ZEB': 1, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'ZEB': 1, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'BCat': 0, 'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'BCat': 0, 'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SNAIL': 1, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'ZEB': 1, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SMAD': 1, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SMAD': 1, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'SMAD': 1, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'PAK': 0, 'TCF_LEF': 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TCF_LEF': 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, 'TCF_LEF': 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('BCat', 'TCF_LEF'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('BCat', 'TCF_LEF'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, 'HGFR': 1, 'miR200': 0},
 {'ECad': 0, 'FAK_SRC_b1': 0, 'HGFR': 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'SNAIL': 1, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ZEB': 1, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'FAK_SRC_b1': 0, 'SLUG': 1, ('PI3K', 'PAK'): 1},
 {'FAK_SRC_b1': 0, 'ZEB': 1, ('PI3K', 'PAK'): 1},
 {'FAK_SRC_b1': 0, 'SNAIL': 1, ('PI3K', 'PAK'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'ECad': 0, 'FAK_SRC_b1': 0, ('PI3K', 'PAK'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('PI3K', 'PAK'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {'FAK_SRC_b1': 0, ('PI3K', 'PAK'): 1, ('SLUG', 'ECad'): 1},
 {'ITG_AB': 1, 'PAK': 0, ('RPTP', 'JNK'): 0},
 {'ITG_AB': 1, 'PAK': 0, ('SNAIL', 'miR200'): 1},
 {'ITG_AB': 1, 'PAK': 0, ('ZEB', 'miR200'): 1},
 {'ITG_AB': 1, 'PAK': 0, ('FAK_SRC_b2', 'RPTP'): 1},
 {'ITG_AB': 1, 'PAK': 0, 'TGFB': 1},
 {'ITG_AB': 1, 'PAK': 0, 'TGFBR': 1},
 {'ITG_AB': 1, 'PAK': 0, ('TGFB', 'TGFB'): 1},
 {'ITG_AB': 1, 'PAK': 0, ('RPTP_L', 'RPTP_L'): 0},
 {'ITG_AB': 1, 'PAK': 0, ('TGFBR', 'SMAD'): 1},
 {'ITG_AB': 1, 'PAK': 0, 'ZEB': 1},
 {'ITG_AB': 1, 'PAK': 0, 'SNAIL': 1},
 {'ITG_AB': 1, 'PAK': 0, 'SLUG': 1},
 {'CSL': 1, 'ITG_AB': 1, 'PAK': 0},
 {'ITG_AB': 1, 'JNK': 1, 'PAK': 0},
 {'ITG_AB': 1, 'PAK': 0, 'SMAD': 1},
 {'ITG_AB': 1, 'PAK': 0, 'RPTP_L': 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('RPTP', 'JNK'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('SNAIL', 'miR200'): 1},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'miR200'): 1},
 {'ITG_AB': 1, ('FAK_SRC_b2', 'RPTP'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('RPTP_L', 'RPTP_L'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('TGFBR', 'SMAD'): 1},
 {'ITG_AB': 1, 'ZEB': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, 'SNAIL': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, 'SLUG': 1, ('FA_b1', 'FA_b2'): 0},
 {'CSL': 1, 'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, 'JNK': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, 'SMAD': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, 'RPTP_L': 0, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b2'): 1},
 {'FAK_SRC_b2': 1, 'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'ITG_AB': 1, ('CSL', 'SNAIL'): 1, ('FA_b1', 'FA_b2'): 0},
 {'BCat': 0, 'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0},
 {'ECad': 0, 'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'ITG_AB': 1, 'RPTP': 0, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, 'PAK': 0, ('ROS', 'FAK_SRC_b2'): 1},
 {'FAK_SRC_b2': 1, 'ITG_AB': 1, 'PAK': 0},
 {'ITG_AB': 1, 'PAK': 0, ('SMAD', 'SNAIL'): 1},
 {'ITG_AB': 1, 'PAK': 0, ('CSL', 'SNAIL'): 1},
 {'BCat': 0, 'ITG_AB': 1, 'PAK': 0},
 {'ECad': 0, 'ITG_AB': 1, 'PAK': 0},
 {'ITG_AB': 1, 'PAK': 0, ('SLUG', 'ECad'): 1},
 {'ITG_AB': 1, 'PAK': 0, ('ZEB', 'ECad'): 1},
 {'ITG_AB': 1, 'PAK': 0, 'RPTP': 0},
 {'SMAD': 1, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('SMAD', 'SNAIL'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {'ECad': 0, 'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {'PAK': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'PAK': 0, 'miR200': 0, ('EGFR', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('HGFR', 'FAK_SRC_b1'): 1},
 {'BCat': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {('BCat', 'TCF_LEF'): 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'TCF_LEF': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {'ECad': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('SLUG', 'ECad'): 1},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('ZEB', 'ECad'): 1},
 {'miR200': 0, ('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {('EGFR', 'FAK_SRC_b1'): 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'FAK_SRC_b1': 1, 'PAK': 0, ('miR200', 'SLUG'): 0},
 {'ITG_AB': 1, 'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('TCF_LEF', 'SNAIL'): 0},
 {'ITG_AB': 1, 'miR200': 0, ('FA_b1', 'FA_b2'): 0},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('miR200', 'SLUG'): 0},
 {'ITG_AB': 1, 'PAK': 0, 'TCF_LEF': 0},
 {'ITG_AB': 1, 'PAK': 0, ('BCat', 'TCF_LEF'): 0},
 {'ITG_AB': 1, 'PAK': 0, ('TCF_LEF', 'SNAIL'): 0},
 {'ITG_AB': 1, 'PAK': 0, 'miR200': 0},
 {'ITG_AB': 1, 'PAK': 0, ('miR200', 'SLUG'): 0},
 {'ITG_AB': 1, 'PAK': 0, ('JNK', 'SNAIL'): 1},
 {'ITG_AB': 1, ('FA_b1', 'FA_b2'): 0, ('JNK', 'SNAIL'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {'PAK': 0, 'miR200': 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'ECad': 0, 'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {'PAK': 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('ROS', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SNAIL', 'miR200'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'miR200'): 1},
 {'CSL': 1, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'SLUG': 1, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'ZEB': 1, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'SNAIL': 1, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TGFBR', 'SMAD'): 1},
 {'SMAD': 1, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SMAD', 'SNAIL'): 1},
 {'BCat': 0, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'miR200': 0, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('BCat', 'TCF_LEF'): 0, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'TCF_LEF': 0, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'ECad': 0, ('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {('FA_b1', 'FA_b2'): 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0},
 {'PAK': 0, 'miR200': 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'ECad': 0, 'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('TCF_LEF', 'SNAIL'): 0},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('ZEB', 'ECad'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('SLUG', 'ECad'): 1},
 {'PAK': 0, ('ITG_AB', 'FAK_SRC_b1'): 1, ('miR200', 'SLUG'): 0}]
