Target = {'AJ_b1': 0, 'AJ_b2': 0, 'FA_b1': 1, 'FA_b2': 1, 'FA_b3': 0}
#Control strategies using percolation
cs = [{'ROS': 1, ('RAP1', 'ITG_AB'): 0},
 {'ITG_AB': 0, 'ROS': 1},
 {('RAP1', 'ITG_AB'): 0, ('ROS', 'ROS'): 1},
 {'ITG_AB': 0, ('ROS', 'ROS'): 1},
 {'ROS': 1, ('FA_b1', 'FA_b3'): 0},
 {'ROS': 1, ('FA_b2', 'FA_b3'): 0},
 {'ROS': 1, ('PAK', 'FA_b3'): 0},
 {'ROS': 1, ('ECM', 'ECM'): 0},
 {('ECM', 'ECM'): 0, ('ROS', 'ROS'): 1},
 {'ROS': 1, ('FAK_SRC_b1', 'FA_b3'): 0},
 {('FAK_SRC_b1', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {'ROS': 1, ('ITG_AB', 'FA_b3'): 0},
 {'ECM': 0, 'ROS': 1},
 {('PAK', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FA_b1', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {('FA_b2', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {'ECM': 0, ('ROS', 'ROS'): 1},
 {('ITG_AB', 'FA_b3'): 0, ('ROS', 'ROS'): 1},
 {'ROS': 1, ('FAK_SRC_b1', 'RAP1'): 0},
 {('FAK_SRC_b1', 'RAP1'): 0, ('ROS', 'ROS'): 1},
 {'RAP1': 0, 'ROS': 1},
 {'RAP1': 0, ('ROS', 'ROS'): 1}]
